# E-Commerce Supply Chain Analysis
# Project Portfolio: E-Commerce Supply Chain Analysis using R-Studio

'Introduction:
This project focuses on analyzing the E-Commerce Supply Chain Analysis. 
As data scientists, we aim to provide valuable insights and information to help 
Company ABCs stakeholders make informed decisions. While the business problem 
and task might vary in real-world scenarios, this project will showcase various 
R-Studio data science techniques and visualizations to gain meaningful insights 
from the dataset. Lets investigate the analysis and explore the data to uncover 
valuable information for Company ABCs supply chain.

Project Objectives: The Project aim is to:

1. Analyzing Revenue by Product Type:
Investigating the revenue generated by different product types to understand 
their contribution to overall sales.
Identifying valuable patterns and trends in customer preferences to inform 
marketing and product strategies.

2. Unraveling Sales by Product Type:
Analyzing sales data to determine each product types sales share and volumes.
Uncovering valuable market trends to assist businesses in making data-driven 
decisions for maximizing profits.

3. Exploring Revenue from Shipping Carriers:
Evaluating the revenue generated by different shipping carriers to identify 
efficient and cost-effective options for shipping and delivery.

4. Analyzing Revenue by SKU (Stock Keeping Unit):
Examining SKU-specific data to gain insights into the performance of individual
products.
Empowering businesses to optimize their inventory strategies based on SKU 
performance.

5. Understanding Shipping Costs of Carriers:
Analyzing shipping costs to identify areas for cost optimization while 
maintaining high-quality service.

6. Cost Distribution by Transportation Modes:
Breaking down costs across different transportation modes to assess logistics 
efficiency.

7. Assessing Defect Rates during Shipping:
Investigating defect rates during shipping to ensure improved customer 
satisfaction and identify areas of improvement in the shipping process.'

'DATA

The data was accessed here: 

https://github.com/areeb399/E-Commerce-Sales-Analysis 

It contains 100 raw and 24 columns, including numerical, categorical and binary 
variables.'

# Install the Libraries 
# install.packages("readxl")
library(readxl)
library(ggplot2)
library(dplyr)

# Setting working directory 
setwd("D:/Portfolio/Paython and Machine Learning/Data Science Portfolio")

# Read Data 
df <- read.csv("supply_chain_data.csv") 
print(df)

# Show first 5 row data
head(df)

# Show least 5 row data
tail(df)

# Summarize data 
summary(df)

# Remove rows with any missing values (NaN) from the data frame df
df <- na.omit(df)
print(df)

# Checking for missing values in the data frame df
missing_values_matrix <- is.na(df)
print(missing_values_matrix)

# Count the number of missing (NA) values in each column of the data frame df
missing_counts <- colSums(is.na(df))
print(missing_counts)

print(names(df))

# Create the scatter plot with a linear regression line and color-coded points based on 'Product type'
# Replace 'df' with the name of your data frame and 'Price' and 'Revenue generated' with the corresponding column names in your data frame
ggplot(df, aes(x = Price, y = Revenue.generated, color = Product.type )) +
  geom_point() +                   # Add scatter plot points
  geom_smooth(method = "lm", se = FALSE) +  # Add linear regression line without confidence interval
  labs(x = "Price", y = "Revenue Generated", title = "Price of Products and Revenue Generated", color = "Product Type") +
  theme_minimal()                 # Optional: Apply a minimal theme for the plot

# Conclusions: 
'Skincare Products:
There is a positive correlation between the price of skincare products and 
the revenue generated. As the price of skincare products increases, the revenue 
generated also increases significantly. This indicates that customers might 
be willing to spend more on skincare products, leading to a substantial 
increase in revenue for the company.

Cosmetics Products:
There is a negative correlation between the price of cosmetics products and 
the revenue generated. As the price of cosmetics products increases, 
the revenue generated tends to decrease. This suggests that customers might 
be more price-sensitive when it comes to cosmetics products, and higher prices
could lead to reduced sales and lower revenue.

Hair Care Products:
 Similar to cosmetics products, there is a negative correlation between 
the price of hair care products and the revenue generated. However, the 
negative impact of price on revenue is less pronounced compared to cosmetics. 
While higher prices may still affect revenue negatively, the slope of the 
relationship is minor, indicating that the effect is not as strong as for 
cosmetics products.'

print(names(df))

# Aggregate the data to get the total number of products sold for each product type
aggregated_data <- df %>%
  group_by(Product.type) %>%
  summarise(Total_Sold = sum(Number.of.products.sold))

# Calculate the total of total sold
total_total_sold <- sum(aggregated_data$Total_Sold)

# Calculate the percentage for each product type
aggregated_data <- aggregated_data %>%
  mutate(Percentage = (Total_Sold / total_total_sold) * 100)

# Create a pie chart with the aggregated data and labels
ggplot(aggregated_data, aes(x = "", y = Total_Sold, fill = Product.type)) +
  geom_bar(stat = "identity") +
  coord_polar(theta = "y") +
  labs(x = NULL, y = NULL, fill = "Product Type", title = "Number of Products Sold by Product Type") +
  theme_void() +
  theme(legend.position = "right") +
  geom_text(aes(label = paste0(Total_Sold, " (", round(Percentage, 2), "%)")), position = position_stack(vjust = 0.5))

# Conclusions:
'Skincare products have the highest sales share, accounting for 
approximately 44.97% of the total products sold. This corresponds to 
a total of 20,731 product items sold.

Haircare products constitute approximately 29.53% of the total product 
sales, with a total of 13,611 product items sold.

Cosmetics make up approximately 25.5% of the total product sales, amounting
to 11,757 product items sold.' 

print(names(df))

# Aggregate the data to get the total Revenue generated  for each Shipping Carriers 
Carriers_data <- df %>%
  group_by(Shipping.carriers) %>%
  summarise(Total_revenue = sum(Revenue.generated))

# Calculate the total of Revenue generated
total_generated_revenue <- sum(Carriers_data$Total_revenue)
print(total_generated_revenue)

# Calculate the percentage for each product type
Carriers_data <- Carriers_data %>%
  mutate(Percentage = (Total_revenue / total_generated_revenue) * 100)

# Bar plot for Percentage with value labels
ggplot(Carriers_data, aes(x = Shipping.carriers, y = Percentage, fill = Shipping.carriers)) +
  geom_bar(stat = "identity") +
  labs(x = "Shipping Carriers", y = "Total Revenue (Percentage)", title = "Percentage of Total Revenue by Shipping Carriers") +
  theme_minimal()+
  geom_text(aes(label = paste0(round(Total_revenue, 1), " (", round(Percentage, 1), "%)")), position = position_stack(vjust = 0.5))

'CONCLUSIONS:
Carrier B has the highest share in generating revenue, accounting for 
approximately 43.3%. This corresponds to a total revenue of 250,094.

Carrier C accounts for approximately 32% of the revenue, with a total 
revenue of 184,880.2.

Carrier A makes up approximately 24.7% of the revenue, amounting to 142,630.' 

print(names(df))

# Line Plot Revenue Generated by each SKU  
ggplot(df, aes(x = SKU, y = Revenue.generated, group = 1)) +
  geom_line() +
  geom_point() +  # Add circle dots at each data point
  labs(x = "SKU", y = "Revenue Generated", title = "Generated Revenue") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 7))  # Rotate x-axis labels by 90 degrees

print(names(df))

# Aggregate the data to get the total Shipping Costs for each Shipping Carriers 
Shipping_data <- df %>%
  group_by(Shipping.carriers) %>%
  summarise(Total_shipping_costs = sum(Shipping.costs))

# Calculate the total of Shipping Costs
total_shipping_costs <- sum(Shipping_data$Total_shipping_costs)
print(total_shipping_costs)

# Calculate the percentage for each product type
Shipping_data <- Shipping_data %>%
  mutate(Percentage = (Total_shipping_costs / total_shipping_costs) * 100)

# Bar plot for Percentage with value labels
ggplot(Shipping_data, aes(x = Shipping.carriers, y = Percentage, fill = Shipping.carriers)) +
  geom_bar(stat = "identity") +
  labs(x = "Shipping Carriers", y = "Total Shipping Costs (Percentage)", title = "Percentage of Shipping Costs by Shipping Carriers") +
  theme_minimal()+
  geom_text(aes(label = paste0(round(Total_shipping_costs, 1), " (", round(Percentage, 1), "%)")), position = position_stack(vjust = 0.5))

'CONCLUSIONS:

Carrier B has the highest share 42.7%. This corresponds to a total shipping 
costs of 236.8.

Carrier C accounts for 29.3% of the shipping costs, with a total 
cost of 162.3.

Carrier A makes up 28.7% of the shipping costs, amounting to 155.5.' 

print(names(df))

# Aggregate the data to get the total  Costs for each Transportation Modes 
Transportation_data <- df %>%
  group_by(Transportation.modes) %>%
  summarise(Total_costs = sum(Costs))

# Calculate the total transporting Costs
total_transport_costs <- sum(Transportation_data$Total_costs)
print(total_transport_costs)

# Calculate the percentage for each Transportation Mode by Costs
Transportation_data <- Transportation_data %>%
  mutate(Percentage = (Total_costs / total_transport_costs) * 100)

# Bar plot for Percentage with value labels
ggplot(Transportation_data, aes(x = Transportation.modes, y = Total_costs, fill = Transportation.modes)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(Total_costs, 1)), position = position_stack(vjust = 0.5), color = "black", size = 4) +
  labs(x = "Transportation modes", y = "Total Costs", title = "Transportation Mode by Costs") +
  theme_minimal()
  
# Pie plot with ggplot
ggplot(Transportation_data, aes(x = "", y = Total_costs, fill = Transportation.modes)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  geom_text(aes(label = paste0(round(Total_costs, 1), " (", round(Total_costs/sum(Total_costs)*100, 1), "%)")),
            position = position_stack(vjust = 0.5), color = "black", size = 4) +
  labs(x = NULL, y = NULL, title = "Transportation Mode by Costs") +
  theme_minimal()

'CONCLUSIONS: Based on the aggregated data visualization, 
the transportation modes can be ranked by their cost as follows:
- Road: 30.3% ($16,048.2)
- Rail: 28.7% ($15,168.9)
- Air: 27.6% ($14,604.5)
- Sea: 13.4% ($7,102.93)'

print(names(df))

# Aggregate the data to get the Defect Rate for each Product Type 
def_data <- df %>%
  group_by(Product.type) %>%
  summarise(Def_Rate = sum(Defect.rates))

# Bar plot for Percentage with value labels
ggplot(def_data, aes(x = Product.type, y = Def_Rate, fill = Product.type)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(Def_Rate, 1)), position = position_stack(vjust = 0.5), color = "black", size = 4) +
  labs(x = "Product type", y = "Defect rates", title = "Defect Rate for each Product Type") +
  theme_minimal()

'CONCLUSIONS: Based on the bar plot visualization, it is evident that:
- Skincare products have the highest defect rate value (93.39),
- Haircare products in the second position (84.43),
- Cosmetics with the lowest defect rate (49.90).' 


# SUMMARY OF CONCLUSSIONS AND FINDINGS

'1. Analyzing Revenue by Product Type:
a). Skincare Products: There is a positive correlation between the price 
of skincare products and the revenue generated. As the price of skincare 
products increases, the revenue generated also increases significantly. 
This indicates that customers might be willing to spend more on skincare 
products, leading to a substantial increase in revenue for the company.
b). Cosmetics Products: There is a negative correlation between the price 
of cosmetics products and the revenue generated. As the price of cosmetics 
products increases, the revenue generated tends to decrease. This suggests 
that customers might be more price-sensitive when it comes to cosmetics 
products, and higher prices could lead to reduced sales and lower revenue.
c). Hair Care Products: Similar to cosmetics products, there is a negative 
correlation between the price of hair care products and the revenue generated. 
However, the negative impact of price on revenue is less pronounced compared 
to cosmetics. While higher prices may still affect revenue negatively, 
the slope of the relationship is minor, indicating that the effect is not 
as strong as for cosmetics products.

2. Unraveling Sales by Product Type:
a). Skincare products have the highest sales share, accounting for 
approximately 44.97% of the total products sold. This corresponds to a total 
of 20,731 product items sold.
b). Haircare products constitute approximately 29.53% of the total product 
sales, with a total of 13,611 product items sold.
c). Cosmetics make up approximately 25.5% of the total product sales, 
amounting to 11,757 product items sold.

3. Exploring Revenue from Shipping Carriers:
a). Carrier B has the highest share in generating revenue, accounting 
for approximately 43.3%. This corresponds to a total revenue of 250,094.
b). Carrier C accounts for approximately 32% of the revenue, with a total 
revenue of 184,880.2.
c). Carrier A makes up approximately 24.7% of the revenue, amounting 
to 142,630.

4. Analyzing Revenue by SKU (Stock Keeping Unit):
Examining SKU-specific data to gain insights into the performance of 
individual products.
Empowering businesses to optimize their inventory strategies based on SKU 
performance.

5. Understanding Shipping Costs of Carriers:
a). Carrier B has the highest share 42.7%. This corresponds to a total 
shipping costs of 236.8.
b). Carrier C accounts for 29.3% of the shipping costs, with a total cost 
of 162.3.
c). Carrier A makes up 28.7% of the shipping costs, amounting to 155.5.

6. Cost Distribution by Transportation Modes:
Conclusions based on the aggregated data visualization, the transportation 
modes can be ranked by their cost as follows:
a). Road: 30.3% (16,048.2)
b). Rail: 28.7% (15,168.9)
c). Air: 27.6% (14,604.5)
d). Sea: 13.4% (7,102.93)

7. Assessing Defect Rates during Shipping:
Conclusions based on the bar plot visualization, it is evident that:
a). Skincare products have the highest defect rate value (93.39),
b). Haircare products in the second position (84.43),
c). Cosmetics with the lowest defect rate (49.90).